#!/bin/bash
# script/bootstrap: Resolve all dependencies that the application requires to run.

set -e

cd $(dirname "$0")/..

if [ -f ".ruby-version" ] && [ -z "$(rbenv version-name 2>/dev/null)" ]; then
  echo "==> Installing Ruby…"
  rbenv install --skip-existing
  which bundle >/dev/null 2>&1  || {
    gem install bundler
    rbenv rehash
  }
fi

if [ -f "Gemfile" ]; then
  echo "==> Installing gem dependencies…"
  bundle check --path vendor/gems >/dev/null 2>&1  || {
    bundle install --path vendor/gems --quiet --without production
  }
fi

/usr/bin/env ruby <<-EORUBY
require 'rubygems'
require 'bundler/setup'
require 'dm-migrations'
require File.expand_path('../lib/tables', __FILE__)

DataMapper.auto_migrate!
EORUBY
